# Terminal configuration
CONFIG_SHELL=y
CONFIG_DEVMEM_SHELL=y

# GPIO configuration
CONFIG_GPIO=y
CONFIG_GPIO_SHELL=y

# Flash configuration
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_SPI_NOR=y
CONFIG_FLASH_SHELL=y

# RAM configuration
CONFIG_MEMC=y
CONFIG_MEMC_STM32=y

# C++ support
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_NEWLIB_LIBC=y
